package com.ntros.core.ecs.store;

import java.util.Arrays;
import java.util.BitSet;

import static com.ntros.AppConstants.CREATURES_MAX_CAPACITY;
import static com.ntros.core.ecs.data.Direction.NO_DIR;
import static com.ntros.core.ecs.data.Motive.WANDER;

/**
 * SoA storage for creatures: component arrays plus slot allocation (freelist + alive bitset).
 * Deferred birth/death queues live in {@link LifecycleRequests}.
 */
public class CreatureStore {

  // on spawn: set bits and fields, allocate on the freelist
  // on kill: clear idx on freelist, flip bit, clear arrays
  // good for sparse maps
  private final BitSet alive = new BitSet(CREATURES_MAX_CAPACITY);
  private int freeCount;

  private final int[] freeList = new int[CREATURES_MAX_CAPACITY];

  // all indexed by creatureId
  final float[] x = new float[CREATURES_MAX_CAPACITY];
  final float[] y =
      new float
          [CREATURES_MAX_CAPACITY]; // position (float: smooth movement, casts to tile via (int))
  final float[] energy = new float[CREATURES_MAX_CAPACITY]; // life budget; 0 = starved

  final short[] age = new short[CREATURES_MAX_CAPACITY];

  // index into a Species table of tuning constants
  final byte[] species = new byte[CREATURES_MAX_CAPACITY];

  // intention mechanics for a target system to execute, generated by the BehaviorSystem
  // dir tells the agent what direction it should take to find the motive;
  // motive tells the agent what it wants to do;
  final byte[] intentDir = new byte[CREATURES_MAX_CAPACITY];
  final byte[] intentMotive = new byte[CREATURES_MAX_CAPACITY];

  /// Spatial index: per-tile intrusive linked lists, rebuilt once per tick by SpatialIndexSystem.
  /// cellHead[tile] = id of first creature on that tile (-1 = none); nextInCell[id] = next id on
  /// the same tile. Makes creatureAt O(1) instead of a scan over all alive ids.
  private int[] cellHead;
  private final int[] nextInCell = new int[CREATURES_MAX_CAPACITY];
  // cells touched by the last rebuild, so clearing is O(alive), not O(world)
  private final int[] usedCells = new int[CREATURES_MAX_CAPACITY];
  private int usedCellCount;
  private int indexWidth;

  public CreatureStore() {
    freeCount = CREATURES_MAX_CAPACITY;

    // Reverse order so popping from the end allocates IDs 0, 1, 2, ...
    for (int i = 0; i < CREATURES_MAX_CAPACITY; i++) {
      freeList[i] = CREATURES_MAX_CAPACITY - 1 - i;
    }
  }

  /** Rebuilds the per-tile index from current positions. Call after movement, before queries. */
  public void rebuildSpatialIndex(int width, int height) {
    int size = width * height;
    if (cellHead == null || cellHead.length != size) {
      cellHead = new int[size];
      java.util.Arrays.fill(cellHead, -1);
      usedCellCount = 0;
    }
    indexWidth = width;

    // clear only occupiers, not the whole world
    for (int i = 0; i < usedCellCount; i++) {
      cellHead[usedCells[i]] = -1;
    }
    usedCellCount = 0;

    // insert all live creatures
    for (int id = alive.nextSetBit(0); id >= 0; id = alive.nextSetBit(id + 1)) {
      // compute creature's position
      int cell = (int) y[id] * width + (int) x[id];

      // if no creatures in the chain, mark the cell
      if (cellHead[cell] == -1) {
        usedCells[usedCellCount++] = cell;
      }
      // for each creature on an occupied cell, make its ID point to the current head[cell], then
      // overwrite the head[cell] = id
      // This creates a chain in nextInCell, where the id's are linked. cellHead[cell] contains the
      // start id.
      // The rest of the chain is found in nextInCell[id1] = id2 -> nextInCell[id2] = id3 ...
      // nextInCell[idn] -> -1, which is the end of the chain
      nextInCell[id] = cellHead[cell];
      cellHead[cell] = id;
    }
  }

  public int spawn() {
    if (freeCount == 0) {
      return -1;
    }
    int creatureId = freeList[--freeCount];
    alive.set(creatureId);
    return creatureId;
  }

  // For Testing. Remove after
  public int[] getCellHead() {
    return cellHead;
  }

  public int[] getNextInCell() {
    return nextInCell;
  }

  public int[] getUsedCells() {
    return usedCells;
  }

  public int getUsedCellCount() {
    return usedCellCount;
  }

  public int getIndexWidth() {
    return indexWidth;
  }

  /**
   * @return id of a living creature standing on tile (cx, cy), or -1. O(1) via the spatial index;
   *     falls back to a linear scan if the index was never built (e.g. in isolated tests).
   */
  public int creatureAt(int cx, int cy) {
    if (cellHead != null) {
      return cellHead[cy * indexWidth + cx];
    }
    for (int id = alive.nextSetBit(0); id >= 0; id = alive.nextSetBit(id + 1)) {
      if ((int) x[id] == cx && (int) y[id] == cy) {
        return id;
      }
    }
    return -1;
  }

  public void kill(int creatureId) {
    alive.clear(creatureId);
    freeList[freeCount++] = creatureId;
  }

  public void clearIntents() {
    // clear with default states
    Arrays.fill(intentDir, (byte) NO_DIR.ordinal());
    Arrays.fill(intentMotive, (byte) WANDER.ordinal());
  }

  public byte[] intentDir() {
    return intentDir;
  }

  public byte[] intentMotive() {
    return intentMotive;
  }

  public BitSet getAlive() {
    return alive;
  }

  public int[] getPrimitiveAlive() {
    return alive.stream().toArray();
  }

  public float[] energy() {
    return energy;
  }

  public short[] age() {
    return age;
  }

  public byte[] species() {
    return species;
  }

  public float[] x() {
    return x;
  }

  public float[] y() {
    return y;
  }
}
